export const defaultRoster = [
  {
    name: "Geese",
    class: "SHD",
    level: 68,
    warden: 2,
    active: true,
    tags: ["erudite"],
  },
  {
    name: "Snarf",
    class: "PAL",
    level: 67,
    warden: 2,
    active: true,
    tags: ["dwarf"],
  },
  {
    name: "Phatos",
    class: "CLR",
    level: 67,
    warden: 0,
    active: true,
    tags: ["high-elf"],
  },
  {
    name: "Huffpo",
    class: "DRU",
    level: 67,
    warden: 0,
    active: true,
    tags: ["halfling"],
  },
  {
    name: "Chacha",
    class: "SHM",
    level: 66,
    warden: 0,
    active: true,
    tags: ["iksar"],
  },
  {
    name: "Dellingr",
    class: "WIZ",
    level: 68,
    warden: 2,
    active: true,
    tags: ["erudite"],
  },
  {
    name: "Difa",
    class: "MAG",
    level: 67,
    warden: 2,
    active: true,
    tags: ["dark-elf", "tank"],
  },
  {
    name: "Guta",
    class: "NEC",
    level: 67,
    warden: 2,
    active: true,
    tags: ["iksar"],
  },
  {
    name: "Delulu",
    class: "ENC",
    level: 66,
    warden: 0,
    active: true,
    tags: ["erudite"],
  },
  {
    name: "Rodeo",
    class: "MNK",
    level: 67,
    warden: 2,
    active: true,
    tags: ["iksar"],
  },
  {
    name: "Kwok",
    class: "BST",
    level: 67,
    warden: 2,
    active: true,
    tags: ["troll"],
  },
  {
    name: "Lala",
    class: "BRD",
    level: 66,
    warden: 0,
    active: true,
    tags: ["wood-elf"],
  },
  {
    name: "Rizzt",
    class: "RNG",
    level: 65,
    warden: 0,
    active: true,
    tags: ["human"],
  },
  {
    name: "Oldboy",
    class: "BER",
    level: 65,
    warden: 0,
    active: true,
    tags: ["dwarf"],
  },
  {
    name: "Yeti",
    class: "WAR",
    level: 65,
    warden: 0,
    active: true,
    tags: ["ogre"],
  },
];
