export const defaultRoster = [
  {
    id: "_CJeUVhpYmjgo3_EoKosz",
    name: "Geese",
    class: "SHD",
    level: 68,
    warden: 2,
    active: true,
  },
  {
    id: "r6m8dzSL0bKdAg2MrPtsd",
    name: "Snarf",
    class: "PAL",
    level: 67,
    warden: 2,
    active: true,
  },
  {
    id: "IW_MgOOgH3hij9oD7R5Qb",
    name: "Phatos",
    class: "CLR",
    level: 67,
    warden: 0,
    active: true,
  },
  {
    id: "mUCyHH-b43FOc2y90eS5F",
    name: "Huffpo",
    class: "DRU",
    level: 67,
    warden: 0,
    active: true,
  },
  {
    id: "yKkL30CJ85HTvsMNmzMaD",
    name: "Chacha",
    class: "SHM",
    level: 66,
    warden: 0,
    active: true,
  },
  {
    id: "stE7_KhSfcg2tgYi-CfcT",
    name: "Dellingr",
    class: "WIZ",
    level: 68,
    warden: 2,
    active: true,
  },
  {
    id: "kfpPNVzz9mx8mVSr6ViSR",
    name: "Difa",
    class: "MAG",
    level: 67,
    warden: 2,
    active: true,
  },
  {
    id: "2E1jRW8Q2EGvaB_CzM2wy",
    name: "Guta",
    class: "NEC",
    level: 67,
    warden: 2,
    active: true,
  },
  {
    id: "UPt3pF3CIldEgEPPreoig",
    name: "Delulu",
    class: "ENC",
    level: 66,
    warden: 0,
    active: true,
  },
  {
    id: "bg7zHRKCgt1hLZFe0GVJy",
    name: "Rodeo",
    class: "MNK",
    level: 67,
    warden: 2,
    active: true,
  },
  {
    id: "-22XQ_TWy55V3iO1P0fO6",
    name: "Kwok",
    class: "BST",
    level: 67,
    warden: 2,
    active: true,
  },
  {
    id: "pKcrQT1ACv_baPK41JLIx",
    name: "Lala",
    class: "BRD",
    level: 66,
    warden: 0,
    active: true,
  },
  {
    id: "MJUnAEBUsvquWh0HCu_yK",
    name: "Rizzt",
    class: "RNG",
    level: 65,
    warden: 0,
    active: true,
  },
  {
    id: "lLERYSLHeUQ-x4_A4vsDi",
    name: "Oldboy",
    class: "BER",
    level: 65,
    warden: 0,
    active: true,
  },
  {
    id: "Vf132thf2wylIDfci3DQj",
    name: "Yeti",
    class: "WAR",
    level: 65,
    warden: 0,
    active: true,
  },
];
